const paymentIntent = {
  id: "pi_3RL2VWCHAEfMqzvo0h3tvxPC",
  object: "payment_intent",
  amount: 388,
  amount_capturable: 0,
  amount_details: { tip: {} },
  amount_received: 388,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: "automatic_async",
  client_secret: "pi_3RL2VWCHAEfMqzvo0h3tvxPC_secret_jGocXvDq0WpSk8kQnvew1pniC",
  confirmation_method: "automatic",
  created: 1746364982,
  currency: "usd",
  customer: null,
  description: null,
  last_payment_error: null,
  latest_charge: "ch_3RL2VWCHAEfMqzvo0G7ivEvS",
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: "pm_1RL2VVCHAEfMqzvofjpwukIp",
  payment_method_configuration_details: null,
  payment_method_options: {
    card: {
      installments: null,
      mandate_options: null,
      network: null,
      request_three_d_secure: "automatic",
    },
  },
  payment_method_types: ["card"],
  presentment_details: {
    presentment_amount: 49032,
    presentment_currency: "bdt",
  },
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: null,
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: "succeeded",
  transfer_data: null,
  transfer_group: null,
};

const sessionDetails = {
  id: "cs_test_a1S36kIOujyczeHxeSos5kWnasxXaBU6qQqzCnP5qDOcv1RHe4FD4lLDJg",
  object: "checkout.session",
  adaptive_pricing: { enabled: true },
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 388,
  amount_total: 388,
  automatic_tax: {
    enabled: false,
    liability: null,
    provider: null,
    status: null,
  },
  billing_address_collection: "required",
  cancel_url: "http://localhost:3000",
  client_reference_id: "cma2w9fdw0000y488rmeuh4dm",
  client_secret: null,
  collected_information: { shipping_details: null },
  consent: null,
  consent_collection: null,
  created: 1746364937,
  currency: "usd",
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: null,
  customer_creation: "if_required",
  customer_details: {
    address: {
      city: "dhaka",
      country: "BD",
      line1: "Dhaka",
      line2: null,
      postal_code: null,
      state: null,
    },
    email: "shuvonagorik@gmail.com",
    name: "shubhankar",
    phone: null,
    tax_exempt: "none",
    tax_ids: [],
  },
  customer_email: "shuvonagorik@gmail.com",
  discounts: [],
  expires_at: 1746451336,
  invoice: null,
  invoice_creation: {
    enabled: false,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      issuer: null,
      metadata: {},
      rendering_options: null,
    },
  },
  livemode: false,
  locale: null,
  metadata: {
    mediaId: "cma6tg57a0001y4gp1xifowef",
    email: "shuvonagorik@gmail.com",
    priceType: "buy",
    userId: "cma2w9fdw0000y488rmeuh4dm",
  },
  mode: "payment",
  payment_intent: "pi_3RL2VWCHAEfMqzvo0h3tvxPC",
  payment_link: null,
  payment_method_collection: "if_required",
  payment_method_configuration_details: {
    id: "pmc_1RKuOQCHAEfMqzvo90hWHVtU",
    parent: null,
  },
  payment_method_options: { card: { request_three_d_secure: "automatic" } },
  payment_method_types: ["card", "link"],
  payment_status: "paid",
  permissions: null,
  phone_number_collection: { enabled: false },
  presentment_details: {
    presentment_amount: 49032,
    presentment_currency: "bdt",
  },
  recovered_from: null,
  saved_payment_method_options: null,
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_options: [],
  status: "complete",
  submit_type: null,
  subscription: null,
  success_url: "http://localhost:3000",
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: "hosted",
  url: null,
  wallet_options: null,
};
